services:
  app:
    build:
      context: .
    env_file:
      - .env.local
    depends_on:
      - redis
      - mongodb
    ports:
      - "${APP_PORT}:${APP_PORT}"
  redis:
    image: redis:7.4-alpine
    command: redis-server --save "" --appendonly no
    env_file:
      - .env.local
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  mongodb:
    image: mongo:8.0
    command: ["mongod", "--port", "${MONGODB_PORT}"]
    env_file:
      - .env.local
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
